[package]
name = "optn-ui"
version = "1.7.3"
edition = "2021"
license = "GPL-3.0-only"
description = "Leptos/WASM frontend for OPTN Wallet."

[[bin]]
name = "optn-ui"
path = "src/main.rs"

[features]
default = []
tauri-transport = ["dep:optn-transport-tauri"]

[dependencies]
leptos = { version = "0.8.20", features = ["csr"] }
optn-app = { path = "../optn-app", version = "=1.7.3" }
optn-transport = { path = "../optn-transport", version = "=1.7.3" }
optn-transport-tauri = { path = "../optn-transport-tauri", version = "=1.7.3", optional = true }
console_error_panic_hook = "0.1"
web-sys = { version = "0.3", features = ["Window", "Crypto"] }
