[workspace]
resolver = "2"
members = [
  "crates/optn-app",
  "crates/optn-platform",
  "crates/optn-platform-native",
  "crates/optn-platform-apple",
  "crates/optn-runtime",
  "crates/optn-transport",
  "crates/optn-transport-tauri",
  "crates/optn-ui",
  "xtask",
]
exclude = [
  "crates/optn-cli",
  "crates/optn-core",
  "src-tauri",
]
default-members = [
  "crates/optn-app",
  "crates/optn-platform",
  "crates/optn-platform-native",
  "crates/optn-platform-apple",
  "crates/optn-runtime",
  "crates/optn-transport",
  "crates/optn-transport-tauri",
  "crates/optn-ui",
  "xtask",
]

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "s"
strip = true
