// SeedCash → OPTN, checked against frames SeedCash itself produced.
//
// Everything else in this suite tests our encoder against our decoder, which
// proves they agree with each other and nothing more. These frames came out of
// SeedCash's own `src/seedcash/helpers/ur2` encoder at commit 2771a9f, driven
// the way `encode_qr.py:280` drives it — `UR("crypto-psbt", self.psbt)`, the
// raw PSBT bytes straight into the UR CBOR field, with no BCR-2020-006 byte
// string around them.
//
// The fixture is regenerated by running that encoder, not by running ours.

import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { UrPsbtScanner } from '../urPsbt';

type Fixture = {
  psbt_hex: string;
  single: string;
} & Record<string, { seq_len: number; frames: string[] }>;

const fixture = JSON.parse(
  readFileSync(
    fileURLToPath(new URL('./fixtures/seedcash-ur-frames.json', import.meta.url)),
    'utf8'
  )
) as Fixture;

const DENSITIES = ['50', '100', '200', '400'] as const;

function drain(frames: string[], scanner = new UrPsbtScanner()) {
  for (const frame of frames) {
    const progress = scanner.receive(frame);
    if (progress.complete && progress.psbt) return progress.psbt;
  }
  return null;
}

describe('a signed PSBT coming back from SeedCash', () => {
  it.each(DENSITIES)(
    'is recovered from frames SeedCash produced at fragment length %s',
    (density) => {
      const recovered = drain(fixture[density].frames);
      expect(recovered, `no PSBT recovered at density ${density}`).not.toBeNull();
      expect(Buffer.from(recovered!).toString('hex')).toBe(fixture.psbt_hex);
    }
  );

  it('is recovered from a single-frame UR', () => {
    const scanner = new UrPsbtScanner();
    const progress = scanner.receive(fixture.single);
    expect(progress.complete).toBe(true);
    expect(Buffer.from(progress.psbt!).toString('hex')).toBe(fixture.psbt_hex);
  });

  it('survives the misreads a camera makes on a long animated scan', () => {
    // The reason this test exists. A signed PSBT is bigger than the unsigned
    // one, so it takes more frames, so the chance of at least one unreadable
    // read approaches certainty. A half-caught frame throws out of the
    // bytewords decoder; treating that as fatal made the longest transfers the
    // least likely to ever finish.
    //
    // The fountain decoder keeps every part it has already accepted, so
    // dropping the bad frame and continuing still recovers the payload.
    const clean = fixture['50'].frames;
    const withMisreads = clean.flatMap((frame, index) =>
      index % 3 === 1
        ? ['UR:CRYPTO-PSBT/9-13/GARBAGEGARBAGEGARBAGE', frame]
        : [frame]
    );

    const scanner = new UrPsbtScanner();
    const recovered = drain(withMisreads, scanner);

    expect(recovered, 'misreads must not prevent recovery').not.toBeNull();
    expect(Buffer.from(recovered!).toString('hex')).toBe(fixture.psbt_hex);
    expect(
      scanner.damagedFrames,
      'the misreads should be counted, not silently swallowed'
    ).toBeGreaterThan(0);
  });

  it('ignores another device QR that wanders into view', () => {
    // A crypto-hdkey is the other thing these devices show. It must not end
    // the scan in progress.
    const frames = fixture['50'].frames;
    const withStray = [
      frames[0],
      'UR:CRYPTO-HDKEY/OYADGDJOJKIDJYZMAXBKBYCSCTDSDPEEFR',
      ...frames.slice(1),
    ];
    const recovered = drain(withStray);
    expect(recovered).not.toBeNull();
    expect(Buffer.from(recovered!).toString('hex')).toBe(fixture.psbt_hex);
  });

  it('counts nothing as damaged on a clean scan', () => {
    const scanner = new UrPsbtScanner();
    drain(fixture['50'].frames, scanner);
    expect(scanner.damagedFrames).toBe(0);
  });
});
