// Generates a base64-embedded copy of tiny-secp256k1's WASM binary so it can
// be instantiated synchronously (new WebAssembly.Module/Instance, both
// synchronous constructors when bytes are already in memory) instead of via
// the ESM-wasm-import-proposal syntax tiny-secp256k1 ships by default, which
// needs vite-plugin-wasm + vite-plugin-top-level-await -- and that combo's
// output can't be downleveled to the conservative target the mobile/web
// build needs for old Android WebView compatibility. Same wasm binary,
// different (synchronous, plain-JS) loading mechanism. Re-run this whenever
// tiny-secp256k1 is upgraded.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const wasmPath = resolve(
  __dirname,
  '../node_modules/tiny-secp256k1/lib/secp256k1.wasm'
);
const outPath = resolve(
  __dirname,
  '../src/platform/web/secp256k1WasmBase64.generated.ts'
);

const bytes = readFileSync(wasmPath);
const base64 = bytes.toString('base64');

const out = `// GENERATED by scripts/generate-secp256k1-wasm-base64.mts -- do not hand-edit.
// Base64 copy of node_modules/tiny-secp256k1/lib/secp256k1.wasm (same file
// desktop loads via vite-plugin-wasm), embedded so it's available
// synchronously at module-evaluation time -- see
// src/platform/web/tinySecp256k1SyncLoader.ts for why.
export const SECP256K1_WASM_BASE64 = '${base64}';
`;

writeFileSync(outPath, out);
console.log(
  `Wrote ${outPath} (${(bytes.length / 1024).toFixed(1)} KB source -> ${(out.length / 1024).toFixed(1)} KB base64)`
);
